export interface Word {
  id: string;
  kanji: string;
  kana: string;
  romaji: string;
  meaning: string;
}

export const words: Word[] = [
  { id: "sakura", kanji: "桜", kana: "さくら", romaji: "sakura", meaning: "樱花" },
  { id: "umi", kanji: "海", kana: "うみ", romaji: "umi", meaning: "大海" },
  { id: "sora", kanji: "空", kana: "そら", romaji: "sora", meaning: "天空" },
  { id: "hikari", kanji: "光", kana: "ひかり", romaji: "hikari", meaning: "光" },
  { id: "yama", kanji: "山", kana: "やま", romaji: "yama", meaning: "山" },
  { id: "kawa", kanji: "川", kana: "かわ", romaji: "kawa", meaning: "河流" },
  { id: "mizu", kanji: "水", kana: "みず", romaji: "mizu", meaning: "水" },
  { id: "hi", kanji: "火", kana: "ひ", romaji: "hi", meaning: "火" },
  { id: "tsuki", kanji: "月", kana: "つき", romaji: "tsuki", meaning: "月亮" },
  { id: "hoshi", kanji: "星", kana: "ほし", romaji: "hoshi", meaning: "星星" },
  { id: "kaze", kanji: "風", kana: "かぜ", romaji: "kaze", meaning: "风" },
  { id: "ame", kanji: "雨", kana: "あめ", romaji: "ame", meaning: "雨" },
  { id: "yuki", kanji: "雪", kana: "ゆき", romaji: "yuki", meaning: "雪" },
  { id: "kumo", kanji: "雲", kana: "くも", romaji: "kumo", meaning: "云" },
  { id: "tori", kanji: "鳥", kana: "とり", romaji: "tori", meaning: "鸟" },
  { id: "hana", kanji: "花", kana: "はな", romaji: "hana", meaning: "花" },
  { id: "ki", kanji: "木", kana: "き", romaji: "ki", meaning: "树" },
  { id: "kusa", kanji: "草", kana: "くさ", romaji: "kusa", meaning: "草" },
  { id: "inu", kanji: "犬", kana: "いぬ", romaji: "inu", meaning: "狗" },
  { id: "neko", kanji: "猫", kana: "ねこ", romaji: "neko", meaning: "猫" },
  { id: "tori", kanji: "鳥", kana: "とり", romaji: "tori", meaning: "鸟" },
  { id: "sakana", kanji: "魚", kana: "さかな", romaji: "sakana", meaning: "鱼" },
  { id: "hon", kanji: "本", kana: "ほん", romaji: "hon", meaning: "书" },
  { id: "kami", kanji: "紙", kana: "かみ", romaji: "kami", meaning: "纸" },
  { id: "fune", kanji: "船", kana: "ふね", romaji: "fune", meaning: "船" },
  { id: "kuruma", kanji: "車", kana: "くるま", romaji: "kuruma", meaning: "汽车" },
  { id: "ie", kanji: "家", kana: "いえ", romaji: "ie", meaning: "家" },
  { id: "gakkou", kanji: "学校", kana: "がっこう", romaji: "gakkou", meaning: "学校" },
  { id: "shigoto", kanji: "仕事", kana: "しごと", romaji: "shigoto", meaning: "工作" },
  { id: "tomodachi", kanji: "友達", kana: "ともだち", romaji: "tomodachi", meaning: "朋友" },
  { id: "kazoku", kanji: "家族", kana: "かぞく", romaji: "kazoku", meaning: "家人" },
  { id: "chichi", kanji: "父", kana: "ちち", romaji: "chichi", meaning: "父亲" },
  { id: "haha", kanji: "母", kana: "はは", romaji: "haha", meaning: "母亲" },
  { id: "ani", kanji: "兄", kana: "あに", romaji: "ani", meaning: "哥哥" },
  { id: "ane", kanji: "姉", kana: "あね", romaji: "ane", meaning: "姐姐" },
  { id: "otouto", kanji: "弟", kana: "おとうと", romaji: "otouto", meaning: "弟弟" },
  { id: "imouto", kanji: "妹", kana: "いもうと", romaji: "imouto", meaning: "妹妹" },
  { id: "kodomo", kanji: "子供", kana: "こども", romaji: "kodomo", meaning: "孩子" },
  { id: "otoko", kanji: "男", kana: "おとこ", romaji: "otoko", meaning: "男人" },
  { id: "onna", kanji: "女", kana: "おんな", romaji: "onna", meaning: "女人" },
  { id: "hito", kanji: "人", kana: "ひと", romaji: "hito", meaning: "人" },
  { id: "kami", kanji: "神", kana: "かみ", romaji: "kami", meaning: "神" },
  { id: "tatemono", kanji: "建物", kana: "たてもの", romaji: "tatemono", meaning: "建筑物" },
  { id: "machi", kanji: "町", kana: "まち", romaji: "machi", meaning: "城镇" },
  { id: "mura", kanji: "村", kana: "むら", romaji: "mura", meaning: "村庄" },
  { id: "kuni", kanji: "国", kana: "くに", romaji: "kuni", meaning: "国家" },
  { id: "sekai", kanji: "世界", kana: "せかい", romaji: "sekai", meaning: "世界" },
  { id: "jikan", kanji: "時間", kana: "じかん", romaji: "jikan", meaning: "时间" },
  { id: "asa", kanji: "朝", kana: "あさ", romaji: "asa", meaning: "早上" },
  { id: "hiru", kanji: "昼", kana: "ひる", romaji: "hiru", meaning: "白天" },
  { id: "yoru", kanji: "夜", kana: "よる", romaji: "yoru", meaning: "夜晚" },
  { id: "haru", kanji: "春", kana: "はる", romaji: "haru", meaning: "春天" },
  { id: "natsu", kanji: "夏", kana: "なつ", romaji: "natsu", meaning: "夏天" },
  { id: "aki", kanji: "秋", kana: "あき", romaji: "aki", meaning: "秋天" },
  { id: "fuyu", kanji: "冬", kana: "ふゆ", romaji: "fuyu", meaning: "冬天" },
  { id: "hi", kanji: "日", kana: "ひ", romaji: "hi", meaning: "太阳" },
  { id: "getsuyoubi", kanji: "月曜日", kana: "げつようび", romaji: "getsuyoubi", meaning: "星期一" },
  { id: "kayoubi", kanji: "火曜日", kana: "かようび", romaji: "kayoubi", meaning: "星期二" },
  { id: "suiyoubi", kanji: "水曜日", kana: "すいようび", romaji: "suiyoubi", meaning: "星期三" },
  { id: "mokuyoubi", kanji: "木曜日", kana: "もくようび", romaji: "mokuyoubi", meaning: "星期四" },
  { id: "kinyoubi", kanji: "金曜日", kana: "きんようび", romaji: "kinyoubi", meaning: "星期五" },
  { id: "doyoubi", kanji: "土曜日", kana: "どようび", romaji: "doyoubi", meaning: "星期六" },
  { id: "nichiyoubi", kanji: "日曜日", kana: "にちようび", romaji: "nichiyoubi", meaning: "星期日" },
  { id: "tsukimi", kanji: "月見", kana: "つきみ", romaji: "tsukimi", meaning: "赏月" },
  { id: "hanami", kanji: "花見", kana: "はなみ", romaji: "hanami", meaning: "赏花" },
  { id: "yukigeshiki", kanji: "雪景色", kana: "ゆきげしき", romaji: "yukigeshiki", meaning: "雪景" },
  { id: "umi_no_sachi", kanji: "海の幸", kana: "うみのさち", romaji: "umi no sachi", meaning: "海鲜" },
  { id: "yama_no_sachi", kanji: "山の幸", kana: "やまのさち", romaji: "yama no sachi", meaning: "山珍" },
  { id: "mizu_no_oto", kanji: "水の音", kana: "みずのおと", romaji: "mizu no oto", meaning: "水声" },
  { id: "kaze_no_koe", kanji: "風の声", kana: "かぜのこえ", romaji: "kaze no koe", meaning: "风声" },
  { id: "tenki", kanji: "天気", kana: "てんき", romaji: "tenki", meaning: "天气" },
  { id: "kion", kanji: "気温", kana: "きおん", romaji: "kion", meaning: "气温" },
  { id: "taiki", kanji: "大気", kana: "たいき", romaji: "taiki", meaning: "大气" },
  { id: "chikyu", kanji: "地球", kana: "ちきゅう", romaji: "chikyuu", meaning: "地球" },
  { id: "wakusei", kanji: "惑星", kana: "わくせい", romaji: "wakusei", meaning: "行星" },
  { id: "ginga", kanji: "銀河", kana: "ぎんが", romaji: "ginga", meaning: "银河" },
  { id: "uchu", kanji: "宇宙", kana: "うちゅう", romaji: "uchuu", meaning: "宇宙" },
  { id: "taiyou", kanji: "太陽", kana: "たいよう", romaji: "taiyou", meaning: "太阳" },
  { id: "tsuki_no_hikari", kanji: "月の光", kana: "つきのひかり", romaji: "tsuki no hikari", meaning: "月光" },
  { id: "taiyou_no_hikari", kanji: "太陽の光", kana: "たいようのひかり", romaji: "taiyou no hikari", meaning: "阳光" },
  { id: "hoshi_no_hikari", kanji: "星の光", kana: "ほしのひかり", romaji: "hoshi no hikari", meaning: "星光" },
  { id: "maboroshi", kanji: "幻", kana: "まぼろし", romaji: "maboroshi", meaning: "幻影" },
  { id: "yume", kanji: "夢", kana: "ゆめ", romaji: "yume", meaning: "梦" },
  { id: "yume", kanji: "夢", kana: "ゆめ", romaji: "yume", meaning: "梦想" },
  { id: "kokoro", kanji: "心", kana: "こころ", romaji: "kokoro", meaning: "心" },
  { id: "tamashii", kanji: "魂", kana: "たましい", romaji: "tamashii", meaning: "灵魂" },
  { id: "seishin", kanji: "精神", kana: "せいしん", romaji: "seishin", meaning: "精神" },
  { id: "karada", kanji: "体", kana: "からだ", romaji: "karada", meaning: "身体" },
  { id: "te", kanji: "手", kana: "て", romaji: "te", meaning: "手" },
  { id: "ashi", kanji: "足", kana: "あし", romaji: "ashi", meaning: "脚" },
  { id: "me", kanji: "目", kana: "め", romaji: "me", meaning: "眼睛" },
  { id: "mimi", kanji: "耳", kana: "みみ", romaji: "mimi", meaning: "耳朵" },
  { id: "hana", kanji: "鼻", kana: "はな", romaji: "hana", meaning: "鼻子" },
  { id: "kuchi", kanji: "口", kana: "くち", romaji: "kuchi", meaning: "嘴巴" },
  { id: "yubi", kanji: "指", kana: "ゆび", romaji: "yubi", meaning: "手指" },
  { id: "kami_no_ke", kanji: "髪の毛", kana: "かみのけ", romaji: "kami no ke", meaning: "头发" },
  { id: "kao", kanji: "顔", kana: "かお", romaji: "kao", meaning: "脸" },
  { id: "ude", kanji: "腕", kana: "うで", romaji: "ude", meaning: "手臂" },
  { id: "hiza", kanji: "膝", kana: "ひざ", romaji: "hiza", meaning: "膝盖" },
  { id: "senaka", kanji: "背中", kana: "せなか", romaji: "senaka", meaning: "背部" },
  { id: "mune", kanji: "胸", kana: "むね", romaji: "mune", meaning: "胸部" },
  { id: "hara", kanji: "腹", kana: "はら", romaji: "hara", meaning: "腹部" },
  { id: "kokoro_no_uchi", kanji: "心の内", kana: "こころのうち", romaji: "kokoro no uchi", meaning: "内心" },
  { id: "kimochi", kanji: "気持ち", kana: "きもち", romaji: "kimochi", meaning: "心情" },
  { id: "kanjou", kanji: "感情", kana: "かんじょう", romaji: "kanjou", meaning: "感情" },
  { id: "ai", kanji: "愛", kana: "あい", romaji: "ai", meaning: "爱" },
  { id: "yuujou", kanji: "友情", kana: "ゆうじょう", romaji: "yuujou", meaning: "友情" },
  { id: "koi", kanji: "恋", kana: "こい", romaji: "koi", meaning: "恋爱" },
  { id: "yorokobi", kanji: "喜び", kana: "よろこび", romaji: "yorokobi", meaning: "喜悦" },
  { id: "kanashimi", kanji: "悲しみ", kana: "かなしみ", romaji: "kanashimi", meaning: "悲伤" },
  { id: "ikari", kanji: "怒り", kana: "いかり", romaji: "ikari", meaning: "愤怒" },
  { id: "kowai", kanji: "怖い", kana: "こわい", romaji: "kowai", meaning: "害怕" },
  { id: "ureshii", kanji: "嬉しい", kana: "うれしい", romaji: "ureshii", meaning: "高兴" },
  { id: "sabishii", kanji: "寂しい", kana: "さびしい", romaji: "sabishii", meaning: "寂寞" },
  { id: "tanoshii", kanji: "楽しい", kana: "たのしい", romaji: "tanoshii", meaning: "快乐" },
  { id: "omoshiroi", kanji: "面白い", kana: "おもしろい", romaji: "omoshiroi", meaning: "有趣" },
  { id: "tsumaranai", kanji: "つまらない", kana: "つまらない", romaji: "tsumaranai", meaning: "无聊" },
  { id: "kirei", kanji: "綺麗", kana: "きれい", romaji: "kirei", meaning: "美丽" },
  { id: "utsukushii", kanji: "美しい", kana: "うつくしい", romaji: "utsukushii", meaning: "美丽" },
  { id: "shizuka", kanji: "静か", kana: "しずか", romaji: "shizuka", meaning: "安静" },
  { id: "nigiyaka", kanji: "賑やか", kana: "にぎやか", romaji: "nigiyaka", meaning: "热闹" },
  { id: "kurai", kanji: "暗い", kana: "くらい", romaji: "kurai", meaning: "黑暗" },
  { id: "akaru", kanji: "明るい", kana: "あかるい", romaji: "akarui", meaning: "明亮" },
  { id: "atarashii", kanji: "新しい", kana: "あたらしい", romaji: "atarashii", meaning: "新" },
  { id: "furui", kanji: "古い", kana: "ふるい", romaji: "furui", meaning: "旧" },
  { id: "ookii", kanji: "大きい", kana: "おおきい", romaji: "ookii", meaning: "大" },
  { id: "chiisai", kanji: "小さい", kana: "ちいさい", romaji: "chiisai", meaning: "小" },
  { id: "nagai", kanji: "長い", kana: "ながい", romaji: "nagai", meaning: "长" },
  { id: "mijikai", kanji: "短い", kana: "みじかい", romaji: "mijikai", meaning: "短" },
  { id: "atsui", kanji: "熱い", kana: "あつい", romaji: "atsui", meaning: "热" },
  { id: "tsumetai", kanji: "冷たい", kana: "つめたい", romaji: "tsumetai", meaning: "冷" },
  { id: "samui", kanji: "寒い", kana: "さむい", romaji: "samui", meaning: "冷" },
  { id: "atatakai", kanji: "暖かい", kana: "あたたかい", romaji: "atatakai", meaning: "温暖" },
  { id: "suzushii", kanji: "涼しい", kana: "すずしい", romaji: "suzushii", meaning: "凉爽" },
  { id: "atarashii_michi", kanji: "新しい道", kana: "あたらしいみち", romaji: "atarashii michi", meaning: "新道路" },
  { id: "furui_ie", kanji: "古い家", kana: "ふるいいえ", romaji: "furui ie", meaning: "旧房子" },
  { id: "ookii_ki", kanji: "大きい木", kana: "おおきいき", romaji: "ookii ki", meaning: "大树" },
  { id: "chiisai_hana", kanji: "小さい花", kana: "ちいさいはな", romaji: "chiisai hana", meaning: "小花" },
  { id: "nagai_michi", kanji: "長い道", kana: "ながいみち", romaji: "nagai michi", meaning: "长路" },
  { id: "mijikai_hanashi", kanji: "短い話", kana: "みじかいはなし", romaji: "mijikai hanashi", meaning: "短故事" },
  { id: "atsui_mizu", kanji: "熱い水", kana: "あついみず", romaji: "atsui mizu", meaning: "热水" },
  { id: "tsumetai_kaze", kanji: "冷たい風", kana: "つめたいかぜ", romaji: "tsumetai kaze", meaning: "冷风" },
  { id: "samui_fuyu", kanji: "寒い冬", kana: "さむいふゆ", romaji: "samui fuyu", meaning: "寒冷的冬天" },
  { id: "atatakai_haru", kanji: "暖かい春", kana: "あたたかいはる", romaji: "atatakai haru", meaning: "温暖的春天" },
  { id: "suzushii_natsu", kanji: "涼しい夏", kana: "すずしいなつ", romaji: "suzushii natsu", meaning: "凉爽的夏天" },
  { id: "tabemono", kanji: "食べ物", kana: "たべもの", romaji: "tabemono", meaning: "食物" },
  { id: "nomimono", kanji: "飲み物", kana: "のみもの", romaji: "nomimono", meaning: "饮料" },
  { id: "kudamono", kanji: "果物", kana: "くだもの", romaji: "kudamono", meaning: "水果" },
  { id: "yasai", kanji: "野菜", kana: "やさい", romaji: "yasai", meaning: "蔬菜" },
  { id: "gohan", kanji: "ご飯", kana: "ごはん", romaji: "gohan", meaning: "米饭" },
  { id: "pan", kanji: "パン", kana: "パン", romaji: "pan", meaning: "面包" },
  { id: "sakana_ryouri", kanji: "魚料理", kana: "さかなりょうり", romaji: "sakana ryouri", meaning: "鱼类料理" },
  { id: "niku_ryouri", kanji: "肉料理", kana: "にくりょうり", romaji: "niku ryouri", meaning: "肉类料理" },
  { id: "yasai_ryouri", kanji: "野菜料理", kana: "やさいりょうり", romaji: "yasai ryouri", meaning: "蔬菜料理" },
  { id: "ocha", kanji: "お茶", kana: "おちゃ", romaji: "ocha", meaning: "茶" },
  { id: "koohii", kanji: "コーヒー", kana: "コーヒー", romaji: "koohii", meaning: "咖啡" },
  { id: "gyuunyuu", kanji: "牛乳", kana: "ぎゅうにゅう", romaji: "gyuunyuu", meaning: "牛奶" },
  { id: "mizu", kanji: "水", kana: "みず", romaji: "mizu", meaning: "水" },
  { id: "sake", kanji: "酒", kana: "さけ", romaji: "sake", meaning: "酒" },
  { id: "biiru", kanji: "ビール", kana: "ビール", romaji: "biiru", meaning: "啤酒" },
  { id: "wain", kanji: "ワイン", kana: "ワイン", romaji: "wain", meaning: "葡萄酒" },
  { id: "ryouri", kanji: "料理", kana: "りょうり", romaji: "ryouri", meaning: "烹饪" },
  { id: "resutoran", kanji: "レストラン", kana: "レストラン", romaji: "resutoran", meaning: "餐厅" },
  { id: "shokudou", kanji: "食堂", kana: "しょくどう", romaji: "shokudou", meaning: "食堂" },
  { id: "kissa_ten", kanji: "喫茶店", kana: "きっさてん", romaji: "kissaten", meaning: "咖啡馆" },
  { id: "supa", kanji: "スーパー", kana: "スーパー", romaji: "supaa", meaning: "超市" },
  { id: "depaato", kanji: "デパート", kana: "デパート", romaji: "depaato", meaning: "百货商店" },
  { id: "konbini", kanji: "コンビニ", kana: "コンビニ", romaji: "konbini", meaning: "便利店" },
  { id: "hon_ya", kanji: "本屋", kana: "ほんや", romaji: "honya", meaning: "书店" },
  { id: "eigakan", kanji: "映画館", kana: "えいがかん", romaji: "eigakan", meaning: "电影院" },
  { id: "bijutsukan", kanji: "美術館", kana: "びじゅつかん", romaji: "bijutsukan", meaning: "美术馆" },
  { id: "toshokan", kanji: "図書館", kana: "としょかん", romaji: "toshokan", meaning: "图书馆" },
  { id: "kouen", kanji: "公園", kana: "こうえん", romaji: "kouen", meaning: "公园" },
  { id: "doubutsuen", kanji: "動物園", kana: "どうぶつえん", romaji: "doubutsuen", meaning: "动物园" },
  { id: "shokubutsuen", kanji: "植物園", kana: "しょくぶつえん", romaji: "shokubutsuen", meaning: "植物园" },
  { id: "umi_no_kouen", kanji: "海の公園", kana: "うみのこうえん", romaji: "umi no kouen", meaning: "海滨公园" },
  { id: "yama_no_kouen", kanji: "山の公園", kana: "やまのこうえん", romaji: "yama no kouen", meaning: "山公园" },
  { id: "machi_no_nakani", kanji: "町の中に", kana: "まちのなかに", romaji: "machi no naka ni", meaning: "在城镇中" },
  { id: "mura_no_soto", kanji: "村の外", kana: "むらのそと", romaji: "mura no soto", meaning: "村庄外" },
  { id: "kuni_no_naka", kanji: "国の中", kana: "くにのなか", romaji: "kuni no naka", meaning: "国家内" },
  { id: "sekai_no_owari", kanji: "世界の終わり", kana: "せかいのおわり", romaji: "sekai no owari", meaning: "世界的尽头" },
  { id: "jikan_no_nagare", kanji: "時間の流れ", kana: "じかんのながれ", romaji: "jikan no nagare", meaning: "时间的流逝" },
  { id: "asa_no_hikari", kanji: "朝の光", kana: "あさのひかり", romaji: "asa no hikari", meaning: "晨光" },
  { id: "hiru_no_hizashi", kanji: "昼の陽射し", kana: "ひるのひざし", romaji: "hiru no hizashi", meaning: "午间的阳光" },
  { id: "yoru_no_yami", kanji: "夜の闇", kana: "よるのやみ", romaji: "yoru no yami", meaning: "夜晚的黑暗" },
  { id: "haru_no_kaze", kanji: "春の風", kana: "はるのかぜ", romaji: "haru no kaze", meaning: "春风" },
  { id: "natsu_no_hizashi", kanji: "夏の陽射し", kana: "なつのひざし", romaji: "natsu no hizashi", meaning: "夏日的阳光" },
  { id: "aki_no_tsuki", kanji: "秋の月", kana: "あきのつき", romaji: "aki no tsuki", meaning: "秋月" },
  { id: "fuyu_no_yuki", kanji: "冬の雪", kana: "ふゆのゆき", romaji: "fuyu no yuki", meaning: "冬雪" },
  { id: "hi_no_de", kanji: "日の出", kana: "ひので", romaji: "hi no de", meaning: "日出" },
  { id: "hi_no_iri", kanji: "日の入り", kana: "ひのいり", romaji: "hi no iri", meaning: "日落" },
  { id: "tsuki_no_yo", kanji: "月の夜", kana: "つきのよる", romaji: "tsuki no yoru", meaning: "月夜" },
  { id: "hoshi_no_sora", kanji: "星の空", kana: "ほしのそら", romaji: "hoshi no sora", meaning: "星空" },
  { id: "kaze_no_uta", kanji: "風の歌", kana: "かぜのうた", romaji: "kaze no uta", meaning: "风之歌" },
  { id: "ame_no_oto", kanji: "雨の音", kana: "あめのおと", romaji: "ame no oto", meaning: "雨声" },
  { id: "yuki_no_shiro", kanji: "雪の城", kana: "ゆきのしろ", romaji: "yuki no shiro", meaning: "雪城" },
  { id: "kumo_no_ue", kanji: "雲の上", kana: "くものうえ", romaji: "kumo no ue", meaning: "云上" },
  { id: "tori_no_uta", kanji: "鳥の歌", kana: "とりのうた", romaji: "tori no uta", meaning: "鸟的歌声" },
  { id: "hana_no_kaori", kanji: "花の香り", kana: "はなのかおり", romaji: "hana no kaori", meaning: "花香" },
  { id: "ki_no_eda", kanji: "木の枝", kana: "きのえだ", romaji: "ki no eda", meaning: "树枝" },
  { id: "kusa_no_hara", kanji: "草の原", kana: "くさのはら", romaji: "kusa no hara", meaning: "草原" },
  { id: "inu_no_koe", kanji: "犬の声", kana: "いぬのこえ", romaji: "inu no koe", meaning: "狗叫声" },
  { id: "neko_no_me", kanji: "猫の目", kana: "ねこのめ", romaji: "neko no me", meaning: "猫的眼睛" },
  { id: "sakana_no_umi", kanji: "魚の海", kana: "さかなのうみ", romaji: "sakana no umi", meaning: "鱼的海" },
  { id: "hon_no_naka", kanji: "本の中", kana: "ほんのなか", romaji: "hon no naka", meaning: "书中" },
  { id: "kami_no_tsubasa", kanji: "紙の翼", kana: "かみのつばさ", romaji: "kami no tsubasa", meaning: "纸翅膀" },
  { id: "fune_no_tabi", kanji: "船の旅", kana: "ふねのたび", romaji: "fune no tabi", meaning: "船旅" },
  { id: "kuruma_no_michi", kanji: "車の道", kana: "くるまのみち", romaji: "kuruma no michi", meaning: "车路" },
  { id: "ie_no_ie", kanji: "家の家", kana: "いえのいえ", romaji: "ie no ie", meaning: "家之家" },
  { id: "gakkou_no_seikatsu", kanji: "学校の生活", kana: "がっこうのせいかつ", romaji: "gakkou no seikatsu", meaning: "学校生活" },
  { id: "shigoto_no_jikan", kanji: "仕事の時間", kana: "しごとのじかん", romaji: "shigoto no jikan", meaning: "工作时间" },
  { id: "tomodachi_no_yume", kanji: "友達の夢", kana: "ともだちのゆめ", romaji: "tomodachi no yume", meaning: "朋友的梦想" },
  { id: "kazoku_no_ai", kanji: "家族の愛", kana: "かぞくのあい", romaji: "kazoku no ai", meaning: "家人的爱" },
  { id: "chichi_no_kokoro", kanji: "父の心", kana: "ちちのこころ", romaji: "chichi no kokoro", meaning: "父亲的心" },
  { id: "haha_no_te", kanji: "母の手", kana: "ははのて", romaji: "haha no te", meaning: "母亲的手" },
  { id: "ani_no_kotoba", kanji: "兄の言葉", kana: "あにのことば", romaji: "ani no kotoba", meaning: "哥哥的话" },
  { id: "ane_no_omoi", kanji: "姉の思い", kana: "あねのおもい", romaji: "ane no omoi", meaning: "姐姐的思念" },
  { id: "otouto_no_warai", kanji: "弟の笑い", kana: "おとうとのわらい", romaji: "otouto no warai", meaning: "弟弟的笑" },
  { id: "imouto_no_namida", kanji: "妹の涙", kana: "いもうとのなみだ", romaji: "imouto no namida", meaning: "妹妹的眼泪" },
  { id: "kodomo_no_yume", kanji: "子供の夢", kana: "こどものゆめ", romaji: "kodomo no yume", meaning: "孩子的梦想" },
  { id: "otoko_no_michi", kanji: "男の道", kana: "おとこのみち", romaji: "otoko no michi", meaning: "男人的道路" },
  { id: "onna_no_kokoro", kanji: "女の心", kana: "おんなのこころ", romaji: "onna no kokoro", meaning: "女人的心" },
  { id: "hito_no_inochi", kanji: "人の命", kana: "ひとのいのち", romaji: "hito no inochi", meaning: "人的生命" }]
