const words = [
  { id: "sakura", kanji: "桜", kana: "さくら", romaji: "sakura", meaning: "樱花" },
  { id: "umi", kanji: "海", kana: "うみ", romaji: "umi", meaning: "大海" },
  { id: "sora", kanji: "空", kana: "そら", romaji: "sora", meaning: "天空" },
  { id: "hikari", kanji: "光", kana: "ひかり", romaji: "hikari", meaning: "光" },
  { id: "tabi", kanji: "旅", kana: "たび", romaji: "tabi", meaning: "旅行" },
  { id: "hoshi", kanji: "星", kana: "ほし", romaji: "hoshi", meaning: "星星" },
  { id: "kaze", kanji: "風", kana: "かぜ", romaji: "kaze", meaning: "风" },
  { id: "ame", kanji: "雨", kana: "あめ", romaji: "ame", meaning: "雨" },
  { id: "yuki", kanji: "雪", kana: "ゆき", romaji: "yuki", meaning: "雪" },
  { id: "mori", kanji: "森", kana: "もり", romaji: "mori", meaning: "森林" },
  { id: "hanabi", kanji: "花火", kana: "はなび", romaji: "hanabi", meaning: "烟花" },
  { id: "yoru", kanji: "夜", kana: "よる", romaji: "yoru", meaning: "夜晚" },
  { id: "asa", kanji: "朝", kana: "あさ", romaji: "asa", meaning: "清晨" },
  { id: "yama", kanji: "山", kana: "やま", romaji: "yama", meaning: "山" },
  { id: "kawa", kanji: "川", kana: "かわ", romaji: "kawa", meaning: "河流" },
  { id: "michi", kanji: "道", kana: "みち", romaji: "michi", meaning: "道路" },
  { id: "tomodachi", kanji: "友達", kana: "ともだち", romaji: "tomodachi", meaning: "朋友" },
  { id: "egao", kanji: "笑顔", kana: "えがお", romaji: "egao", meaning: "笑脸" },
  { id: "kibou", kanji: "希望", kana: "きぼう", romaji: "kibou", meaning: "希望" },
  { id: "mirai", kanji: "未来", kana: "みらい", romaji: "mirai", meaning: "未来" },
];
